# Generated by Django 6.0.3 on 2026-05-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
