# Generated by Django 6.0.3 on 2026-05-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_product_previous_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='previous_price',
        ),
    ]
