# Generated by Django 5.2.11 on 2026-05-06 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_book_available_to_borrow_book_synopsis_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookclub.profile'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookclub.genre'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bookclub.book'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='anon_reviewer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
