# Generated by Django 5.2.11 on 2026-05-06 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_alter_book_contributor_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclub.profile'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
