# Generated by Django 5.2.12 on 2026-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
        ('localevents', '0002_event_capacity_event_image_event_organizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, related_name='organized_events', to='accounts.profile'),
        ),
    ]
